## NumPy

In [1]:
# Installation 
# pip install numpy or
# conda install numpy

In [2]:
#  ** Difference between NumPy array and Python List**

# NumPy's arrays are more compact than Python lists
# If we create list of list array of 1 million records then Python List will take around 20 MB but NumPy will take only 4 MB
# Its faster than Python List 
# NumPy is not just more efficient; it is also more convenient.
# You get a lot of vector and matrix operations, which sometimes allow to avoid unnecessary work in using Python List. NumPy array is also efficiently implemented


### Using NumPy

In [7]:
# Import NumPy

import numpy as np

In [5]:
# Numpy has many built-in functions and capabilities. 
# We won't cover them all but instead we will focus on some of the most important aspects of Numpy for Data Science and Machine learning 


#### Creating NumPy Arrays

In [8]:
myList = [1,2,3,4]

print(myList)

[1, 2, 3, 4]


In [10]:
# Creating NumPy from Python List
np.array(myList)

array([1, 2, 3, 4])

In [ ]:
# Creating Matrix from Python List Of List


In [14]:
myMatrix = [[1,2,3],[4,5,6],[7,8,9]]
print(myMatrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [15]:
np.array(myMatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##### Creating NumPy array in other ways

In [19]:
# arange method
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# first parameter is starting value, second parameter is last value and third value is steps
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [25]:
# Generate arrays of zeros or ones

In [30]:
np.zeros(3)

array([0., 0., 0.])

In [28]:
np.ones(3)

array([1., 1., 1.])

In [33]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [35]:
# ** linspace
# Return evenly spaced numbers over a specified interval.

In [44]:
# This code will create the array of 5 elements starting from 0 with equal space 
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [49]:
np.linspace(0,50,5)

array([ 0. , 12.5, 25. , 37.5, 50. ])

#### Random 

Numpy also has lots of ways to create random number arrays:


In [50]:
# rand

In [54]:
# Create the array of 3 random numbers
np.random.rand(3)

array([0.36577749, 0.65433254, 0.91264676])

In [56]:
# Create the 2D array 3x3 with random numbers
np.random.rand(3,3)

array([[0.12756887, 0.4943401 , 0.12363971],
       [0.39308411, 0.68929868, 0.09089889],
       [0.62375708, 0.90026966, 0.65001517]])

In [57]:
# randint
# Get the any random number between Starting number (inclusive) and End number (exclusive)

In [60]:
np.random.randint(1,10)

9

In [70]:
# Get the 3 random numbers in between 1(inclusive) to 10 (exclusive)
np.random.randint(1,10,4)

array([6, 9, 4, 6])

In [71]:
# Question: What will happen if we pass 20 instead of 4 in above code

#### Array Attributes and Methods

In [8]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [9]:
rArr = np.random.randint(0,25,12)
rArr

array([18,  5, 22, 12, 15, 18, 24, 15, 21,  5, 19,  8])

In [10]:
# Reshape
# Convert the array in a specific shape

In [11]:
rArr.reshape(3,4)

array([[18,  5, 22, 12],
       [15, 18, 24, 15],
       [21,  5, 19,  8]])

In [12]:
# Question: What will happen when we pass 5 instead of 4 in code rArr.reshape(3,4)? 

In [13]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [14]:
rArr

array([18,  5, 22, 12, 15, 18, 24, 15, 21,  5, 19,  8])

In [15]:
# Find the max value in the array
rArr.max()

24

In [16]:
# Find the index of max value in the array
rArr.argmax()

6

In [17]:
rArr.argmin()

1

In [18]:
# Find minimum value in the array
rArr.min()

5

In [23]:
# Shape attribute
# shape attribute will tell you about numpy array shape like 1D, 2D 

In [20]:
rArr.shape

(12,)

In [21]:
rArr = rArr.reshape(3,4)

In [22]:
rArr.shape

(3, 4)

In [26]:
# Ignore some unimportant warnings and make the code clear
import warnings
warnings.filterwarnings('ignore')

#### NumPy Operations
Arithmetic Operations - 
You can easily perform array with array arithmetic, or scalar with array arithmetic.

In [28]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
arr-2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

#### Universal Array Functions

There are essentially just mathematical operations you can use to perform the operation across the array

In [34]:
# Square root
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [35]:
# Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [48]:
# Sign value of arr and like sign we can cos and tan value 
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])